const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');fs.mkdirSync(path.join(root,'test-results'),{recursive:true});const types={'.html':'text/html','.js':'text/javascript'};
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0];if(name==='/config.js'){res.setHeader('Content-Type','text/javascript');return res.end("const GYM_CONFIG={endpoint:'/mock-cloud'};");}const file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.setHeader('Content-Type',types[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,downloadsPath:path.join(root,'test-results'),...(process.env.GYM_TEST_BROWSER?{executablePath:process.env.GYM_TEST_BROWSER}:{})});
 try{
 const context=await browser.newContext({acceptDownloads:true,viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',err=>errors.push(err.message));const vaults=new Map();let failCloud=false;
 await context.route('**/mock-cloud',async route=>{if(failCloud)return route.fulfill({status:503,body:'{}'});const req=route.request(),secret=req.headers()['x-gym-key'],body=req.postDataJSON();if(body.register&&!vaults.has(secret))vaults.set(secret,new Map());const vault=vaults.get(secret);if(body.workouts&&vault){for(const h of body.workouts)if(!vault.has(h.id))vault.set(h.id,h);}await route.fulfill({contentType:'application/json',body:JSON.stringify({exists:!!vault,saved:true,workouts:vault?[...vault.values()]:[],hasMore:false})});});
 await page.clock.install();await page.goto(url);await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));
 assert.equal(await page.locator('#exercises .card').count(),6);assert.equal(await page.getByRole('spinbutton',{name:'Peso Panca inclinata con manubri',exact:true}).inputValue(),'');
 await page.getByRole('spinbutton',{name:'Peso Panca inclinata con manubri',exact:true}).fill('14');
 const chest=page.getByRole('group',{name:'Recupero Panca inclinata con manubri',exact:true});
 await chest.getByRole('button',{name:'Aumenta recupero Panca inclinata con manubri di 30 secondi',exact:true}).click();assert.equal(await chest.locator('.rest-setting').innerText(),'120 s');
 await page.getByRole('checkbox',{name:'Panca inclinata con manubri completato',exact:true}).check();assert.match(await page.locator('#dayProgress').innerText(),/1 \/ 6/);
 await chest.getByRole('button',{name:'Avvia',exact:true}).click();await page.clock.fastForward(31000);await page.reload();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));assert.equal(await chest.getByRole('button',{name:'Pausa',exact:true}).count(),1);assert.match(await chest.locator('.rest-countdown').innerText(),/^01:/);await chest.getByRole('button',{name:'Pausa',exact:true}).click();const paused=await chest.locator('.rest-countdown').innerText();await page.clock.fastForward(31000);assert.equal(await chest.locator('.rest-countdown').innerText(),paused);
 await page.getByRole('button',{name:'B',exact:true}).click();assert.match(await page.locator('#dayProgress').innerText(),/0 \/ 6/);await page.getByRole('button',{name:'A',exact:true}).click();assert.equal(await page.getByRole('checkbox',{name:'Panca inclinata con manubri completato',exact:true}).isChecked(),true);
 await page.reload();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));assert.equal(await page.getByRole('checkbox',{name:'Panca inclinata con manubri completato',exact:true}).isChecked(),true);assert.equal(await chest.locator('.rest-countdown').innerText(),paused);
 await chest.getByRole('button',{name:'Avvia',exact:true}).click();await page.clock.fastForward(121000);assert.equal(await chest.locator('.rest-countdown').innerText(),'Recupero terminato ✓');assert.equal(await page.getByRole('group',{name:'Recupero Rematore con manubri',exact:true}).locator('.rest-countdown').innerText(),'01:30');
 await chest.getByRole('button',{name:'Reset',exact:true}).click();assert.equal(await chest.locator('.rest-countdown').innerText(),'02:00');
 await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 1',exact:true}).fill('12');await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 3',exact:true}).fill('12');await page.getByRole('textbox').fill('<img src=x onerror=alert(1)>');
 await page.getByRole('button',{name:'B',exact:true}).click();await page.getByRole('button',{name:'A',exact:true}).click();assert.equal(await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 1',exact:true}).inputValue(),'12');
 await page.reload();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));assert.equal(await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 3',exact:true}).inputValue(),'12');
 failCloud=true;await page.getByRole('button',{name:'Salva allenamento',exact:true}).click();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('non raggiungibile'));
 assert.match(await page.locator('.suggestion').first().innerText(),/Completa/);assert.equal(await page.locator('#history img').count(),0);assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('gymTrackerV1')))).history[0].exercises[0].reps[1],null);
 failCloud=false;await page.getByRole('button',{name:'Sincronizza',exact:true}).click();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));
 assert.equal([...vaults.values()][0].size,1);await page.getByRole('button',{name:'Sincronizza',exact:true}).click();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));assert.equal([...vaults.values()][0].size,1);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'⬇️ Esporta dati',exact:true}).click();const download=await downloadPromise;fs.mkdirSync(path.join(root,'test-results'),{recursive:true});const backupPath=path.join(root,'test-results','browser-backup.json');await download.saveAs(backupPath);const backup=JSON.parse(fs.readFileSync(backupPath,'utf8'));assert.equal(backup.history.length,1);assert.match(backup.recoveryKey,/^[a-f0-9]{64}$/);
 await page.getByRole('button',{name:'C',exact:true}).click();assert.equal(await page.locator('#exercises .card').count(),8);
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();assert.equal(await page.locator('#exercises .card').count(),8);await context.setOffline(false);
 await page.getByRole('button',{name:'A',exact:true}).click();await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 1',exact:true}).fill('12');await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 2',exact:true}).fill('12');await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 3',exact:true}).fill('12');await page.getByRole('button',{name:'Salva allenamento',exact:true}).click();await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));assert.match(await page.locator('.suggestion').first().innerText(),/16 kg/);
 await page.screenshot({path:path.join(root,'preview.png'),fullPage:false});
 assert.deepEqual(errors,[]);await context.close();

 const migrationContext=await browser.newContext();
 await migrationContext.route('**/mock-cloud',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({exists:true,workouts:[],hasMore:false})}));
 const migrated=await migrationContext.newPage();await migrated.goto(url);await migrated.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));
 const oldDraft={day:'A',drafts:{A:{notes:'Bozza precedente',exercises:[{weight:'35',reps:['12','12','12'],completed:true},{weight:'6',reps:['15'],completed:true},{weight:'14',reps:['8'],restSeconds:120}]},B:{exercises:[{weight:'50'},{weight:'35'},{weight:'35'},{weight:'0'},{weight:'10',reps:['8']},{weight:'0',reps:['15'],completed:true}]},C:{exercises:[{weight:'50',reps:['8']},{weight:'30'},{weight:'8'},{weight:'0'},{weight:'12',reps:['8'],completed:true}]}},workoutStart:null,lastDuration:120000};
 const oldHistory={history:[{id:'old-workout-12345',createdAt:'2026-10-04T12:00:00Z',day:'A',date:'4/10/2026',duration:null,exercises:[{name:'Chest Press',weight:35,reps:[12,12,12]}],notes:''}]};
 await migrated.evaluate(({oldDraft,oldHistory})=>{localStorage.removeItem('gymDraftsV3');localStorage.setItem('gymDraftsV2',JSON.stringify(oldDraft));localStorage.setItem('gymTrackerV1',JSON.stringify(oldHistory));},{oldDraft,oldHistory});
 await migrated.reload();await migrated.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sincronizzato'));
 assert.equal(await migrated.getByRole('spinbutton',{name:'Peso Panca inclinata con manubri',exact:true}).inputValue(),'');
 assert.equal(await migrated.getByRole('checkbox',{name:'Panca inclinata con manubri completato',exact:true}).isChecked(),false);
 assert.equal(await migrated.getByRole('spinbutton',{name:'Croci con manubri su panca serie 1',exact:true}).inputValue(),'15');
 assert.equal(await migrated.getByRole('checkbox',{name:'Croci con manubri su panca completato',exact:true}).isChecked(),true);
 assert.equal(await migrated.getByRole('textbox').inputValue(),'Bozza precedente');
 await migrated.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 1',exact:true}).fill('10');await migrated.getByRole('button',{name:'Salva allenamento',exact:true}).click();
 assert.match(await migrated.locator('#saveStatus').innerText(),/Inserisci il peso/);
 await migrated.getByRole('spinbutton',{name:'Peso Panca inclinata con manubri',exact:true}).fill('14');
 await migrated.getByRole('button',{name:'B',exact:true}).click();assert.equal(await migrated.getByRole('spinbutton',{name:'Peso Leg Press',exact:true}).inputValue(),'');assert.equal(await migrated.getByRole('spinbutton',{name:'Bicipiti con manubri serie 1',exact:true}).inputValue(),'8');
 await migrated.getByRole('button',{name:'C',exact:true}).click();for(const name of ['Lat Machine presa stretta','Rematore alla macchina']){assert.equal(await migrated.getByRole('spinbutton',{name:'Peso '+name,exact:true}).inputValue(),'');assert.equal(await migrated.getByRole('spinbutton',{name:name+' serie 1',exact:true}).inputValue(),'');}
 await migrated.getByRole('button',{name:'A',exact:true}).click();await migrated.reload();assert.equal(await migrated.getByRole('spinbutton',{name:'Peso Panca inclinata con manubri',exact:true}).inputValue(),'14');
 const saved=await migrated.evaluate(()=>({legacy:JSON.parse(localStorage.getItem('gymDraftsV2')),history:JSON.parse(localStorage.getItem('gymTrackerV1'))}));assert.deepEqual(saved.legacy,oldDraft);assert.equal(saved.history.history[0].exercises[0].name,'Chest Press');assert.equal(saved.history.history[0].exercises[0].weight,35);
 await migrationContext.close();console.log('PASS plan migration: old history and drafts retained, matching exercises preserved, changed exercise loads reset, new draft survives reload');

 console.log('PASS browser: exercise timer, pause, expiry, completion persistence, days A/B/C, offline save, cloud retry and export');
 }finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);server.close();process.exitCode=1;});

