const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),A='a'.repeat(64),B='b'.repeat(64);
const workout=(id,day='A')=>({id,day,date:'8/10/2026',createdAt:'2026-10-08T10:00:00Z',duration:null,notes:id,exercises:[{name:'Chest Press',weight:30,reps:[10,10,10]}]});
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0];res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':'text/html');if(name==='/config.js')return res.end("const GYM_CONFIG={endpoint:'/mock-cloud'};");try{res.end(fs.readFileSync(path.join(root,name==='/'?'index.html':name)));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,...(process.env.GYM_TEST_BROWSER?{executablePath:process.env.GYM_TEST_BROWSER}:{})});
try{
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:844}}),page=await context.newPage(),vaults=new Map(),errors=[];
 let unavailable=false,dropWrites=false,blockedKey=null,holdRead=null;
 page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/mock-cloud',async route=>{const req=route.request(),secret=req.headers()['x-gym-key'],body=req.postDataJSON();if(unavailable||secret===blockedKey)return route.fulfill({status:503,body:'{}'});if(body.register&&!vaults.has(secret))vaults.set(secret,new Map());const vault=vaults.get(secret);for(const h of body.workouts||[])if(vault&&!dropWrites&&!vault.has(h.id))vault.set(h.id,h);if(body.offset!==undefined&&holdRead){const wait=holdRead;holdRead=null;await wait;}return route.fulfill({contentType:'application/json',body:JSON.stringify({exists:!!vault,saved:true,workouts:vault?[...vault.values()]:[],hasMore:false})});});
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('sincronizzato'));
 const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('gymTrackerV1')));
 const saved=()=>page.waitForFunction(()=>document.querySelector('#saveFeedback').textContent==='Salvato e sincronizzato ✓');
 const fill=async()=>{await page.getByRole('spinbutton',{name:'Peso Panca inclinata con manubri',exact:true}).fill('14');await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 1',exact:true}).fill('10');};
 const retry=async()=>{await page.locator('details').evaluate(e=>e.open=true);await page.locator('#sync').click();};
 // A successful POST without the record in read-back is not a synchronization confirmation.
 dropWrites=true;await fill();await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('non confermato'));assert.equal((await state()).history.length,1);assert.equal((await state()).acknowledgedIds.length,0);assert.match(await page.locator('#saveFeedback').innerText(),/in attesa/);
 dropWrites=false;await retry();await saved();assert.equal((await state()).acknowledgedIds.length,1);
 // Offline save persists across reload, then reconnect retries without a second save or duplicates.
 unavailable=true;await fill();await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('non confermato'));await page.reload();await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('non confermato'));assert.equal((await state()).history.length,2);assert.equal((await state()).acknowledgedIds.length,1);
 unavailable=false;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await saved();assert.equal((await state()).acknowledgedIds.length,2);assert.equal([...vaults.values()][0].size,2);
 // An additional save during read-back remains pending until the follow-up sync confirms it.
 let release;holdRead=new Promise(r=>release=r);await retry();await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('in corso'));await fill();await page.locator('#save').click();assert.equal((await state()).history.length,3);assert.equal((await state()).acknowledgedIds.length,2);release();await saved();assert.equal((await state()).acknowledgedIds.length,3);assert.equal([...vaults.values()][0].size,3);
 // A local storage failure must leave the entered draft and previous history intact.
 await fill();await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='gymTrackerV1')throw Error('Quota exceeded');return window.originalSetItem.call(this,k,v);};});await page.locator('#save').click();assert.match(await page.locator('#saveStatus').innerText(),/Salvataggio sul dispositivo non riuscito/);assert.equal((await state()).history.length,3);assert.equal(await page.getByRole('spinbutton',{name:'Panca inclinata con manubri serie 1',exact:true}).inputValue(),'10');await page.evaluate(()=>Storage.prototype.setItem=window.originalSetItem);
 // Link two vaults, including a source workout only in cloud and a different target day.
 const local=workout('local-source-123'),cloudOnly=workout('cloud-source-123','B'),target=workout('target-vault-123','C');vaults.set(A,new Map([[cloudOnly.id,cloudOnly]]));vaults.set(B,new Map([[target.id,target]]));
 unavailable=true;await page.evaluate(({A,local})=>{localStorage.setItem('gymTrackerV1',JSON.stringify({history:[local],recoveryKey:A,acknowledgedIds:[]}));localStorage.setItem('gymCloudKeyV1',A);},{A,local});await page.reload();await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('non confermato'));unavailable=false;
 let prompted=B;page.on('dialog',d=>d.accept(d.type()==='prompt'?prompted:undefined));await page.locator('details').evaluate(e=>e.open=true);
 blockedKey=B;await page.locator('#restoreCloud').click();await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('Collegamento non completato'));assert.equal((await state()).recoveryKey,A);assert.equal((await state()).history.length,1);
 blockedKey=null;prompted=url+'/#connect='+B;await page.locator('#restoreCloud').click();await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('Aperture collegate'));assert.equal((await state()).recoveryKey,B);assert.deepEqual(new Set((await state()).history.map(h=>h.id)),new Set([local.id,cloudOnly.id,target.id]));assert.equal(vaults.get(B).size,3);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gymSafetyBackupsV1')).at(-1).recoveryKey),A);
 // Import merges history but never silently changes the current connection to an exported key.
 const imported=workout('import-other-123','B');await page.locator('#fileImport').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({history:[imported],recoveryKey:'c'.repeat(64)}))});await page.waitForFunction(()=>document.querySelector('#archiveSummary').textContent.startsWith('4 allenamenti'));await saved();assert.equal((await state()).recoveryKey,B);assert.equal(vaults.get(B).size,4);
 // Recover the pre-import snapshot retains later records. Recover pre-link identity explicitly.
 await page.locator('#undoArchive').click();await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('Archivio precedente recuperato'));await saved();assert.equal((await state()).history.length,4);assert.equal((await state()).recoveryKey,B);
 await page.evaluate(()=>{const list=JSON.parse(localStorage.getItem('gymSafetyBackupsV1'));localStorage.setItem('gymSafetyBackupsV1',JSON.stringify(list.filter(b=>b.reason==='Collegamento')));});await page.locator('#undoArchive').click();await page.waitForFunction(()=>document.querySelector('#cloudStatus').textContent.includes('sincronizzato'));assert.equal((await state()).recoveryKey,A);assert.equal((await state()).history.length,4);assert.equal(vaults.get(A).size,4);
 assert.deepEqual(errors,[]);await context.close();console.log('PASS reliable saving: read-back acknowledgment, durable pending retry, concurrent saves, storage failure, safe pairing, import and recovery');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
